steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/containers/devops-ia-backend:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/containers/devops-ia-backend:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'devops-ia-backend'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/containers/devops-ia-backend:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=4000'
      - '--set-env-vars=MONGO_DB_URL=${_MONGO_DB_URL},CLIENT_URL=${_CLIENT_URL},SECRET_ACCESS_TOKEN=${_SECRET_ACCESS_TOKEN},ACCESS_TOKEN_EXPIRE=${_ACCESS_TOKEN_EXPIRE},SECRET_REFRESH_TOKEN=${_SECRET_REFRESH_TOKEN},REFRESH_TOKEN_EXPIRE=${_REFRESH_TOKEN_EXPIRE},ML_API_BASE_URL=${_SIMILARITY_URL},BACKEND_URL=${_BACKEND_URL}'
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Get Backend URL'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL_VALUE=$$(gcloud run services describe devops-ia-backend --region=${_REGION} --format='value(status.url)')
        echo $$BACKEND_URL_VALUE > /workspace/BACKEND_URL
        echo "Backend URL: $$BACKEND_URL_VALUE"
  - name: 'curlimages/curl'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        backend_url=$$(cat /workspace/BACKEND_URL)
        curl -sf "$$backend_url/api/users" || curl -sf "$$backend_url/health" || echo 'Note: health check fallback'
  # Chain check: ensure backend can reach Similarity (requires _SIMILARITY_URL)
  - name: 'curlimages/curl'
    id: 'Chain check Similarity from Cloud Build'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ -n "${_SIMILARITY_URL}" ]; then curl -sf "${_SIMILARITY_URL}/health"; else echo 'SIMILARITY_URL not provided, skipping'; fi
images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/containers/devops-ia-backend:$BUILD_ID'
substitutions:
  _REGION: asia-south1
  _MONGO_DB_URL: mongodb+srv://user:pass@cluster/db
  _CLIENT_URL: https://frontend.example.com
  _SIMILARITY_URL: ""
  _BACKEND_URL: "https://devops-ia-backend-226162055882.asia-south1.run.app"
  _SECRET_ACCESS_TOKEN: "your-super-secret-access-token-key-here"
  _ACCESS_TOKEN_EXPIRE: "15m"
  _SECRET_REFRESH_TOKEN: "your-super-secret-refresh-token-key-here"
  _REFRESH_TOKEN_EXPIRE: "7d"
timeout: 1200s
